# 프로파일을 사용할지 지정 (dev, prod 등)
spring:
    profiles:
        active: dev

# Swagger 설정
springdoc:
    api-docs:
        enabled: true
        path: /api-docs
    swagger-ui:
        enabled: true
        path: /swagger-ui.html
    default-produces-media-type: application/json
    writer-with-default-pretty-printer: true
    model-and-view-allowed: true

# 공통 캐시 설정
cache:
    ttl:
        values:
            friends:
                minutes: 15

# 공통 스케줄러 설정
task:
    scheduling:
        pool:
            size: 5

# 공통 WebSocket 설정
websocket:
    endpoint: /ws
    allowed-origins: "*"

# 공통 로그 레벨 설정
logging:
    level:
        org.hibernate.SQL: off
        org.hibernate.type.descriptor.sql.BasicBinder: off
