name: CI

on:
    push:
        branches: [ main, dev ]
    pull_request:
        branches: [ main, dev ]

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: backend

        steps:
            - name: Checkout source code
              uses: actions/checkout@v3

            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                  java-version: '17'
                  distribution: 'temurin'

            - name: Cache Gradle packages
              uses: actions/cache@v3
              with:
                  path: |
                      ~/.gradle/caches
                      ~/.gradle/wrapper
                  key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
                  restore-keys: |
                      ${{ runner.os }}-gradle-

            - name: Grant execute permission to Gradle
              run: chmod +x gradlew

            - name: Create .env from GitHub Secrets
              working-directory: backend
              run: |
                  echo "LOCAL_MYSQL_URL=${{ secrets.LOCAL_MYSQL_URL }}" >> .env
                  echo "LOCAL_MYSQL_USERNAME=${{ secrets.LOCAL_MYSQL_USERNAME }}" >> .env
                  echo "LOCAL_MYSQL_PASSWORD=${{ secrets.LOCAL_MYSQL_PASSWORD }}" >> .env
                  echo "LOCAL_REDIS_HOST=${{ secrets.LOCAL_REDIS_HOST }}" >> .env
                  echo "LOCAL_REDIS_PORT=${{ secrets.LOCAL_REDIS_PORT }}" >> .env
                  echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
                  echo "KAKAO_CLIENT_ID=${{ secrets.KAKAO_CLIENT_ID }}" >> .env
                  echo "KAKAO_CLIENT_SECRET=${{ secrets.KAKAO_CLIENT_SECRET }}" >> .env

            - name: Build with Gradle
              run: ./gradlew build

            - name: Upload JAR artifact
              uses: actions/upload-artifact@v4
              with:
                  name: app-jar
                  path: backend/build/libs/*.jar
