name: CI

on:
    pull_request:
        branches: [ main, develop ]
    push:
        branches: [ main, develop ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout source code
              uses: actions/checkout@v3

            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                  java-version: '17'
                  distribution: 'temurin'

            - name: Grant execute permission to Gradle
              run: chmod +x gradlew

            - name: Build with Gradle
              run: ./gradlew build
